#BNF+IAT 1.0 UTF-8;
!grammar talker;

!slot <want>;
!slot <content>;
!slot <place>;

!start <begintalk>;
<begintalk>:[<want>]<place>|<content>;


<want>:我想要找!id(1)|我想找!id(2)|我找!id(3)|找一下!id(4);


<content>:向前走!id(9)|向前走一步!id(10)|向后走!id(11)|向后走一步!id(11)|向后退!id(12)|向后退一步!id(13)|向左转!id(14)|向左旋转!id(15)|向右转!id(16)|向右旋转!id(17)|你好!id(1001)|你叫什么名字!id(1002)|你多大了!id(1003)|你几岁了!id(1004)|你来自哪里!id(1005)|介绍一下你自己!id(1006)|你自我介绍一下!id(1007)|介绍你自己!id(1008)|再见!id(1009)|很高兴见到你!id(1010)|你会做什么!id(1011)|你会什么!id(1012)|你是谁!id(1013)|快递!id(1014)|介绍重德智能!id(1015)|介绍一下重德智能!id(1015)|你有弟弟吗!id(1016)|你弟弟是谁!id(1017);

<place>:汪鹏!id(1)|常先明!id(2)|常总!id(3)|方洋!id(4)|方总!id(5)|会议!id(6)|会议室!id(7)|张晶!id(8)|财务!id(9)|关闭!id(10)|回去!id(11);